name: final_project
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.1
  dio: ^4.0.6
  connectivity_plus: ^2.2.1
  flutter_easyloading: ^3.0.3
  shimmer: ^2.0.0
  carousel_slider: ^4.0.0
  badges: ^2.0.2
  flutter_launcher_icons: ^0.9.2
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  shared_preferences: ^2.0.13
  webview_flutter: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.10
  hive_generator: ^1.1.2

flutter:
  uses-material-design: true


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/eshop_logo.png"

  assets:
    - assets/
    - assets/images/


